/**
 * Tracker API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.example.fitness.client.models

/**
 * 
 * @param profileImage 
 * @param firstName 
 * @param lastName 
 * @param dateOfBirth 
 * @param gender 
 */
data class EditUserRequest (

    val profileImage: kotlin.ByteArray? = null,
    val firstName: kotlin.String? = null,
    val lastName: kotlin.String? = null,
    val dateOfBirth: java.time.LocalDateTime? = null,
    val gender: Gender? = null
) {
}