/**
 * Tracker API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.example.fitness.client.models


/**
 * 
 * @param lat 
 * @param lon 
 * @param time 
 * @param alt 
 * @param speed 
 */
data class Point (

    val lat: kotlin.Float? = null,
    val lon: kotlin.Float? = null,
    val time: java.time.LocalDateTime? = null,
    val alt: kotlin.Float? = null,
    val speed: kotlin.Float? = null
) {
}