/**
 * Tracker API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.example.fitness.client.models


/**
 * 
 * Values: _0,_1,_2,_3,_4,_5,_6,_7
 */
enum class TrackType(val value: kotlin.Int){
    _0(0),// :/
    _1(1),// :/
    _2(2),// :/
    _3(3),// :/
    _4(4),// :/
    _5(5),// :/
    _6(6),// :/
    _7(7);// :/
}